#!/bin/sh

DIR=./deck/
mkdir -p $DIR
if [ $(ls -ld $DIR | awk '{print $3}') != $USER ]; then
    echo "[ERR] The output folder '$DIR' MUST be owned by you!"
    echo "[ERR] Please change ownership to yourself ('sudo chown $USER $DIR'), or"
    echo "[ERR] remove '$DIR' completely ('sudo rm -rf $DIR')."
    exit 1
fi
MARKDECK_USER=$(ls -ldn $DIR | awk '{print $3 ":" $4}') docker-compose up
