[package]
name = "markdeck"
version = "0.1.0"
authors = ["Arne Hilmann <arne@hilmann.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
grass = "0.10.4"

[dependencies]
rust-embed = { version = "5.8.0", features = ["compression"] }
grass = "0.10.4"
rusync = "0.7.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
glob = "0.3.0"

actix = "0.10"
actix-codec = "0.3"
actix-web = "3"
actix-web-actors = "3"
actix-files = "0.3"
awc = "2"
env_logger = "0.8"
futures = "0.3.1"
bytes = "0.5.3"

notify = "4.0.15"
anyhow = "1.0"
ctrlc = { version = "3.1.8", features = ["termination"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }