#!/bin/bash

echo
echo "scaffolding markdeck"
echo

echo "checking environment"
curl --version > /dev/null 2>&1 || { echo "Please install 'curl' first!"; exit 2; }
docker-compose version > /dev/null 2>&1 || { echo "Please install 'docker-compose' first! On MacOS, use 'brew install docker-compose'"; exit 2; }
echo "ok"
echo

CURL="curl -# -S -f"
MASTER=https://raw.githubusercontent.com/arnehilmann/markdeck/master/example/minimal

echo "pulling minimal config"
for F in start stop docker-compose.yaml update-markdeck Makefile; do
    $CURL -O $MASTER/$F
done
chmod a+x start stop update-markdeck
echo

echo "pulling minimal example"
mkdir -p assets/css/fonts
for F in slides.md assets/css/slides.scss assets/css/fonts/EBGaramond12-Regular.ttf assets/css/fonts/xkcd-script.ttf assets/css/fonts/Inconsolata-Regular.ttf; do
    [[ -e $F ]] || $CURL -o $F $MASTER/$F
done
echo

echo "pulling docker images"
docker-compose pull
echo

echo "starting markdeck"
docker-compose up
