#!/bin/bash
curl -O https://raw.githubusercontent.com/arnehilmann/markdeck/master/docker-compose.yaml
for F in slides.md assets/css/slides.scss assets/css/fonts/EBGaramond12-Regular.ttf assets/css/fonts/xkcd-script.ttf assets/css/fonts/Inconsolata-Regular.ttf; do
    curl -o $F https://raw.githubusercontent.com/arnehilmann/markdeck/master/example/minimal/$F
done

docker-compose pull
docker-compose up

echo "open http://localhost:8080"
echo "edit slides.md"
