#!/bin/bash
set -e -E -u

while read -r line || [[ -n "$line" ]]; do
    if echo "$line" | grep -q "<script src="; then
        src=$(echo "$line" | sed "s/^.*<script.*src=['\"]//;s/['\"].*$//")
        echo
        echo "<!-- EXTERNAL JAVASCRIPT: $src -->"
        echo "<script>"
        cat $src
        echo "</script>"
    elif echo "$line" | grep -q "<link .*stylesheet"; then
        src=$(echo "$line" | sed "s/^.*<link.* href=['\"]//;s/['\"].*$//")
        echo
        echo "<!-- EXTERNAL STYLESHEET: $src -->"
        echo "<style>"
        while read -r cssline; do
            if echo "$cssline" | grep -q "src: .*url(\"fonts.* format"; then
                fontsrc=$(echo "$cssline" | sed "s/.*url(['\"]//;s/['\"].*//")
                fontencoded=$(base64 -w 0 $(dirname $src)/$fontsrc)
                # TODO support more formats, like truetype, ...
                echo "src: url(\"data:font/woff2;charset=utf-8;base64,$fontencoded\") format(\"woff2\");}"
           else
                echo "$cssline"
            fi
        done <$src
        echo "</style>"
    elif echo "$line" | grep -q "<img .*src="; then
        src=$(echo "$line" | sed "s/^.*<img .*src=['\"]//;s/['\"].*$//")
        echo
        echo "<!-- EXTERNAL IMAGE: $src -->"
        echo "$line" | sed "s/ src=\".*//"
        echo "    src=\"data:image/png;base64,$(base64 -w 0 $src)\""
        echo "$line" | sed "s/.* src=\"[^\"]*\"//"
    elif echo "$line" | grep -q "<section .*data-background-image="; then
        src=$(echo "$line" | sed "s/^.*<section .*data-background-image=['\"]//;s/['\"].*$//")
        echo
        echo "<!-- EXTERNAL BACKGROUND IMAGE: $src -->"
        echo "$line" | sed "s/data-background-image=.*//"
        # TODO support more formats, like jpeg, ...
        echo "    data-background-image=\"data:image/png;base64,$(base64 -w 0 $src)\">"
    else
        echo "$line"
    fi
done
