#!/bin/bash
set -e -E -u

while read -r line || [[ -n "$line" ]]; do
    if echo "$line" | grep -q "<script src="; then
        src=$(echo "$line" | sed "s/^.*<script.*src=['\"]//;s/['\"].*$//")
        du -h "$src" >&2
        echo
        echo "<!-- EXTERNAL JAVASCRIPT: $src -->"
        echo "<script>"
        cat $src
        echo "</script>"
    elif echo "$line" | grep -q "<link .*stylesheet"; then
        src=$(echo "$line" | sed "s/^.*<link.* href=['\"]//;s/['\"].*$//")
        du -h "$src" >&2
        echo
        echo "<!-- EXTERNAL STYLESHEET: $src -->"
        echo "<style>"
        while read -r cssline; do
            if echo "$cssline" | grep -q "src: .*url(\"fonts.* format"; then
                fontsrcrel=$(echo "$cssline" | sed "s/.*url(['\"]//;s/['\"].*//")
                fontsrcabs=$(dirname $src)/$fontsrcrel
                du -h "$fontsrcabs" >&2
                fontencoded=$(base64 -w 0 "$fontsrcabs")
                # TODO support more formats, like truetype, ...
                echo "src: url(\"data:font/opentype;charset=utf-8;base64,$fontencoded\") format(\"opentype\");}"
           else
                echo "$cssline"
            fi
        done < $src
        echo "</style>"
    elif echo "$line" | grep -q "<img .*src="; then
        src=$(echo "$line" | sed "s/^.*<img .*src=['\"]//;s/['\"].*$//")
        du -h "$src" >&2
        format=${src##*.}
        echo
        echo "<!-- EXTERNAL IMAGE: $src -->"
        # TODO support formats, which dont need base64 encoding, e.g. svg?!
        if [[ $format = "svg" ]]; then
            cat $src
        else
            echo "$line" | sed "s/ src=\".*//"
            echo "    src=\"data:image/$format;base64,$(base64 -w 0 $src)\""
            echo "$line" | sed "s/.* src=\"[^\"]*\"//"
        fi
    elif echo "$line" | grep -q "<section .*data-background-image="; then
        src=$(echo "$line" | sed "s/^.*<section .*data-background-image=['\"]//;s/['\"].*$//")
        du -h "$src" >&2
        format=${src##*.}
        echo
        echo "<!-- EXTERNAL BACKGROUND IMAGE: $src -->"
        echo "$line" | sed "s/data-background-image=.*//"
        echo "    data-background-image=\"data:image/format;base64,$(base64 -w 0 $src)\">"
    elif echo "$line" | grep -q "<asciinema-player src="; then
        src=$(echo "$line" | sed "s/^.*<asciinema-player src=['\"]//;s/['\"].*$//")
        du -h "$src" >&2
        echo
        echo "<!-- EXTERNAL ASCIINEMA SCRIPT: $src -->"
        echo "<asciinema-player src=\"data:text/json;base64,$(base64 -w 0 $src)\""
    else
        echo "$line"
    fi
done
