#!/bin/bash
set -e -E -u

PORT=8080
PORT_HELPER=8081
ONCE=false

PARAM=${1:-loop}
case $PARAM in
    shell)  bash -i; exit;;
    --once) ONCE=true;;
    loop)   ;;
    *)      echo "unknown parameter '$PARAM' given, aborting here..." && exit 1;;
esac

shopt -s nullglob
esc=$(printf '\033')

function print_usage() {
    echo -e "\n\n\n${esc}[1mmarkdeck $VERSION - $MOTTO${esc}[0m\n"
    echo -e "       ${esc}[1mfor the slides:  open http://localhost:$PORT${esc}[0m"
    echo
    echo -e "for side-by-side view:  open http://localhost:$PORT/explain.html"
    echo -e "     to stop markdeck:  hit Ctrl-C"
    echo
    echo
}

function show_errors() {
    echo '<html><head></head><body><pre>' > /target/index.html
    cat /target/.meta/pandoc.output >> /target/index.html
    echo '</pre></body></html>' >> /target/index.html
    echo -e "${esc}[37m${esc}[43m"
    echo -e "\npandoc crashed\n"
    cat /target/.meta/pandoc.output
    echo -e "${esc}[0m"
    sleep 4
}

if ! $ONCE; then
    print_usage
    touch /target/index.html
fi

[[ -e /source/render-asciiart-filter.config ]] && \
    ASCIIART_CONFIG=/source/render-asciiart-filter.config || \
    ASCIIART_CONFIG=/markdeck/lib/render-asciiart-filter.config
export ASCIIART_CONFIG
export ASCIIART_LIBDIR=/markdeck/lib

while true; do
    cd /target

    make -f /markdeck/Makefile all || show_errors

    $ONCE && break

    if [[ /source -nt /target/index.html ]]; then
        echo -e "\n\n\nchange detected: sources newer than rendered deck, rerendering started...\n\n\n"
        continue
    fi

    sleep .5
    print_usage

    make -f /markdeck/Makefile waitforchanges

    echo -e "\n\n\n\n\n\n\n\n\n\n"
done

echo "done."
