#!/bin/bash
set -e -E -u

SOURCES="/source/slide*.md $(find /source/assets -type d) /source/include-before-body /source/include-after-body"
TARGET="${1}"

if [ ! -e "${TARGET}" ]; then
    exit 1
fi

last_sources=$(echo $SOURCES)
no_change=true
while $no_change; do
    if [[ $(echo $SOURCES) != $last_sources ]]; then
        echo "sources changed!"
        no_change=false
        last_sources=$(echo $SOURCES)
    fi
    for F in $SOURCES; do
        [[ -e $F ]] || continue
        if [[ $F -nt $TARGET ]]; then
            echo $F
            no_change=false
        fi
    done
    $no_change && sleep 1
done

exit 0
