#!/bin/bash
set -e -E -u

PORT=8080
ONCE=false

PARAM=${1:-loop}
case $PARAM in
    shell)  bash -i && exit;;
    --once) ONCE=true;;
    loop)   ;;
    *)      echo "unknown parameter '$PARAM' given, aborting here..." && exit 1;;
esac


$ONCE || live-server --port=$PORT /target &

[[ -e /source/render-asciiart-filter.config ]] && \
    ASCIIART_CONFIG=/source/render-asciiart-filter.config || \
    ASCIIART_CONFIG=/markdeck/lib/render-asciiart-filter.config
export ASCIIART_CONFIG

export ASCIIART_CONFIG
export ASCIIART_LIBDIR=/markdeck/lib

while true; do
    cd /target
    [[ -d /target/rendered ]] || mkdir -p /target/rendered

    echo "-------- rsync output --------"
    rsync -Pav /markdeck/assets /source/assets /target/ || :
    echo "-------- /rsync output --------"
    echo

    echo "-------- config --------"
    echo ASCIIART_CONFIG=$ASCIIART_CONFIG
    title=
    theme=
    transition=
    variant=
    [[ -e /source/config ]] && source /source/config
    MARKDECK_TITLE=${title:-markdeck}
    MARKDECK_THEME=${theme:-simple}
    MARKDECK_TRANSITION=${transition:-slide}
    MARKDECK_VARIANT=${variant:-revealjs}
    MARKDECK_TEMPLATE=/markdeck/template-$MARKDECK_VARIANT.html
    for V in ${!MARKDECK_@}; do
        echo $V=${!V}
    done
    echo "-------- /config --------"
    echo

    echo "-------- pandoc output --------"
    /markdeck/bin/pandoc \
        -f markdown \
        -t html5 \
        --standalone \
        --template=$MARKDECK_TEMPLATE \
        --section-divs \
        --lua-filter /markdeck/lib/render-asciiart-filter.lua \
        --lua-filter /markdeck/lib/$MARKDECK_VARIANT-shortcut-filter.lua \
        --variable theme=$MARKDECK_THEME \
        --variable transition=$MARKDECK_TRANSITION \
        --variable title="$MARKDECK_TITLE" \
        -o /target/index.html \
        /source/slides.md || :
    echo "-------- /pandoc output --------"
    echo
    $ONCE && break

    sleep .5
    echo -e "\n\n\nopen http://localhost:$PORT\n\n(... or use Ctrl-C to stop markdeck)\n\n\n"
    inotifywait -r -q /source/*.md /source/assets/ /source/*config
    echo -e "\n\n\n\n\n\n\n\n\n\n"
done

echo "done."
