#!/bin/bash
set -e -E -u

PORT=8080
ONCE=false

PARAM=${1:-loop}
case $PARAM in
    shell)  bash -i && exit;;
    --once) ONCE=true;;
    loop)   ;;
    *)      echo "unknown parameter '$PARAM' given, aborting here..." && exit 1;;
esac


$ONCE || live-server --port=$PORT /target &

export ASCIIART_CONFIG=/source/render-asciiart-filter.config
export ASCIIART_LIBDIR=/md2deck/lib

while true; do
    cd /target
    [[ -d /target/rendered ]] || mkdir -p /target/rendered

    echo "-------- rsync output --------"
    rsync -Pav /source/assets /md2deck/assets /target/ || :
    echo "-------- /rsync output --------"
    echo

    echo "-------- config --------"
    title=
    theme=
    transition=
    variant=
    [[ -e /source/config ]] && source /source/config
    MD2DECK_TITLE=${title:-md2deck}
    MD2DECK_THEME=${theme:-simple}
    MD2DECK_TRANSITION=${transition:-slide}
    MD2DECK_VARIANT=${variant:-revealjs}
    MD2DECK_TEMPLATE=/md2deck/template-$MD2DECK_VARIANT.html
    for V in ${!MD2DECK_@}; do
        echo $V=${!V}
    done
    echo "-------- /config --------"
    echo

    echo "-------- pandoc output --------"
    /md2deck/bin/pandoc \
        -f markdown \
        -t html5 \
        --standalone \
        --template=$MD2DECK_TEMPLATE \
        --section-divs \
        --lua-filter /md2deck/lib/render-asciiart-filter.lua \
        --lua-filter /md2deck/lib/$VARIANT-shortcut-filter.lua \
        --variable theme=$MD2DECK_THEME \
        --variable transition=$MD2DECK_TRANSITION \
        --variable title="$MD2DECK_TITLE" \
        -o /target/index.html \
        /source/slides.md || :
    echo "-------- /pandoc output --------"
    echo
    $ONCE && break

    sleep .5
    echo -e "\n\n\nopen http://localhost:$PORT\n\n(... or use Ctrl-C to stop md2deck)\n\n\n"
    inotifywait -r -q /source/
    echo -e "\n\n\n\n\n\n\n\n\n\n"
done

echo "done."
