#!/bin/bash
set -e -E -u

docker run \
    -v $PWD/../example:/source:ro \
    -v $PWD/slides:/target \
    -v $PWD/markdeck:/markdeck:ro \
    -it \
    --rm \
    --shm-size 1G \
    -p 8080:8080 \
    -p 8081:8081 \
    arne/markdeck \
    $@
