#!/bin/bash
set -e -E -u

docker run \
    -v $PWD:/source:ro \
    -v $PWD/docs:/target \
    -v $PWD/markdeck:/markdeck:ro \
    -it \
    --rm \
    -p 8080:8080 \
    -p 8081:8081 \
    arne/markdeck \
    $@
