version: "3.2"

services:
  markdeck:
    image: "arne/markdeck-pandoc:0.35"
    volumes:
      - type: bind
        source: ./
        target: /source
        read_only: true
      - type: bind
        source: ./deck
        target: /target
      - type: bind
        source: ../src/markdeck
        target: /markdeck
    stdin_open: true
    tty: true
    entrypoint: /bin/sh


  web:
    image: "arne/markdeck-liveserver:0.3"
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./deck
        target: /target
    depends_on: [markdeck]

  pdf:
    image: "arne/markdeck-decktape:0.6"
    volumes:
      - type: bind
        source: ./deck
        target: /slides
    shm_size: 1G
    depends_on: [markdeck, web]

  helper:
    image: "arne/markdeck-helper:0.2"
    ports:
      - "8081:8081"

  standalone:
    image: "arne/markdeck-standalone:0.3"
    volumes:
      - type: bind
        source: ./deck
        target: /target
    depends_on: [web]

  a2sketch:
    image: "arne/a2sketch:0.12"
    volumes:
      - type: bind
        source: ./a2s-custom-types
        target: /custom-types
        read_only: true
    ports:
      - "22753:22753"
