version: "3.2"
services:
  markdeck:
    build:
      context: .
      dockerfile: Dockerfile.pandoc
      args:
        version: 0.51
        motto: the show still must go on
    image: arne/markdeck-pandoc:0.51
    user: nobody
    volumes:
    - type: bind
      source: ./
      target: /source
      read_only: true
    - type: bind
      source: ./deck
      target: /target
  web:
    build:
      context: .
      dockerfile: Dockerfile.liveserver
    image: arne/markdeck-liveserver:0.2
    ports:
    - 8080:8080
    volumes:
    - type: bind
      source: ./deck
      target: /target
    depends_on:
    - markdeck
  pdf:
    build:
      context: .
      dockerfile: Dockerfile.decktape
    image: arne/markdeck-decktape:0.8
    volumes:
    - type: bind
      source: ./deck
      target: /slides
    shm_size: 1G
    depends_on:
    - markdeck
    - web
  standalone:
    build:
      context: .
      dockerfile: Dockerfile.standalone
    image: arne/markdeck-standalone:0.4
    volumes:
    - type: bind
      source: ./deck
      target: /target
    depends_on:
    - web
  friends:
    image: arne/markdown-friends:0.5
    ports:
    - 8081:8081
  a2sketch:
    image: arne/a2sketch:0.11
    volumes:
    - type: bind
      source: ./
      target: /custom-types
      read_only: true
