FROM node:alpine

LABEL maintainer="arne@hilmann.de"

RUN npm install -g live-server && npm cache clean --force

EXPOSE 8080

VOLUME /target
WORKDIR /target

ENTRYPOINT live-server --no-browser --wait=1 --watch=/target/index.html /target
